name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: |
          xcodebuild \
            -project SaturdayQuiz.xcodeproj \
            -scheme SaturdayQuiz \
            -configuration Debug \
            -destination 'generic/platform=tvOS' \
            build
